# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://hamelsmu.github.io/test_3/"

git_url = "https://github.com/hamelsmu/test_3/tree/master/"

def custom_doc_links(name): return None
